# Generated by Django 5.2 on 2025-05-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
