# Generated by Django 5.2 on 2025-05-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_booking_total_harga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_harga',
        ),
        migrations.AddField(
            model_name='kamar',
            name='harga_per_malam',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
            preserve_default=False,
        ),
    ]
