# Generated by Django 5.2 on 2025-05-04 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_remove_booking_total_harga_kamar_harga_per_malam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kamar',
            name='harga_per_malam',
        ),
    ]
