# Generated by Django 5.2 on 2025-05-04 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_kamar_harga_per_malam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kamar',
            old_name='harga',
            new_name='harga_per_malam',
        ),
    ]
