# Generated by Django 5.2 on 2025-05-04 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_rename_harga_kamar_harga_per_malam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kamar',
            old_name='harga_per_malam',
            new_name='harga',
        ),
    ]
