# Generated by Django 5.2 on 2025-05-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_rename_harga_per_malam_kamar_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_harga',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
    ]
