# Generated by Django 5.2 on 2025-05-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_booking_total_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamar',
            name='fasilitas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
