# Generated by Django 5.2 on 2025-05-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
