# Generated by Django 5.2 on 2025-05-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_booking_alamat'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamar',
            name='tersedia',
            field=models.BooleanField(default=True),
        ),
    ]
