# Generated by Django 5.2 on 2025-05-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_kamar_tersedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamar',
            name='stok',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
