# Generated by Django 5.2 on 2025-05-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_kamar_stok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamar',
            name='stok',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
