# Generated by Django 5.2 on 2025-05-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_alter_kamar_stok'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bukti_pembayaran',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='metode_pembayaran',
            field=models.CharField(blank=True, choices=[('e-wallet', 'E-Wallet'), ('va-bank', 'VA Bank')], max_length=20, null=True),
        ),
    ]
